# Permalinks
permalink:      /:year-:month-:day/:title

# Setup
title:          윤두현의 블로그
paginate:       5
baseurl:        
url:            "http://ydh2500.github.io"

# Assets
sass:
  sass_dir:     _sass
  style:        :compressed

# Build settings
markdown:       kramdown

# About
author:
  name:         ydh2500
  url:          http://ydh2500.github.io
  email:        ydh2500@gmail.com

# Custom vars
version:        3.4.1
github:
  repo:         https://github.com/chesterhow/tale

# Gems
plugins:
  - jekyll-paginate
